### ISSUE TITLE
Casbin.NET v2.0.0 Proposal

### ISSUE THREAD

**Issue by sagilio** [casbin/Casbin.NET#101]
Now, Casbin.NET have almost all the main features, we should run to the next stage (v2.0.0), it will include more excited improve and features and many breaking and necessary changes. We will descript and track the detail and procession of the new version here. 

Please note it now was a proposal and you can comment on your opinions and suggestions anytime.

## Features

- [x] 1. Thread-safe model (included policy store). (#76)
- [x] 2. Support pattern feature at default role manager. (#78)
- [x] 3. Support build Incremental role links. (#82)
- [x] 4. Support logging feature. (#116)
- [x] 5. Support the cache feature. (#142)
- [x] 7. Add domain optional support at RBAC APIs. (#114)

### **Structures Improve**

We will change the project structures here, This will provide effective help for future development and maintenance.

- [x] 1. (**Include Breaking Changes**) Unique namespace specification. (#120)
- [x] 2. (**Include Breaking Changes**) Extendibility structure Improve. (#124)
- [x] 3. (**Include Breaking Changes**) Change the way of integrating RBAC API and Management API to one Enforcer. (#56)
- [x] 4. Use interface return and pass arguments. (#137)
- [x] 5. Make assertion properties to public read-only (#79)
- [x]  6. Add cancellationToken optional argument support. (#185)
- [x] 7. Change the workflow of creating a model (#52) 
  
### **Performance Improve**

- [x] 1. Support generic type at Enforce APIs. (#94)
- [x] 4. Quick return of merging effects (#93).

**Comment by krishnaanaril** [comment]
@Sagilio How can I help?

**Comment by Sagilio** [comment]
@krishnaanaril  Of course! Welcome to open issues or pull requests.

**Comment by Leonardo-Ferreira** [comment]
So, how far along are we? where can I help?

**Comment by hsluoyz** [comment]
@sagilio

**Comment by sagilio** [comment]
> So, how far along are we? where can I help?

Thanks! Most features have been merged, but we have some other work:
1. An known load policy bug (https://github.com/casbin/Casbin.NET/issues/183)
2. We need more multithread test cases for the new SyncModel.
3. Update the doc at https://github.com/casbin/casbin-website. Many APIs have been implemented at Casbin.NET, but have not updated the docs.

**Comment by Leonardo-Ferreira** [comment]
so, this has gone a while since an update, what we missing @sagilio?

**Comment by sagilio** [comment]
> so, this has gone a while since an update, what we missing @sagilio?

It just needs to update docs for v2.0 now, the package will release soon.

**Comment by hsluoyz** [comment]
Done
