### ISSUE TITLE
Proposal: Generic type's policy and request

### ISSUE THREAD

**Issue by sagilio** [casbin/Casbin.NET#229]
### **Context and purposes**
Casbin uses a string array to store all policies, so we have ensured the request is always a string. In some situations, we need additional operations to "parse" request values: https://github.com/casbin/casbin/issues/868.
However, this does bring some benefits, all as strings can greatly reduce the complexity of development. like we can provide a clear signature for the custom function:
```csharp
// golang
func (key1 string, key2 string) bool
// csharp
Func<string, string, bool>
```

So this proposal does not completely make the parameters strongly typed, currently only for the following purposes :
- Validate matcher when loading model.
- Lower memory allocation and boxed conversion.
- Provider better ABAC support, like higher performance.
- Prepare for future semantic expansion, like auto-type parse.

### **Roadmap**
- [ ] https://github.com/casbin/Casbin.NET/issues/94 **(Will be included to v2.0)**
- [ ] https://github.com/casbin/Casbin.NET/issues/226
- [ ] https://github.com/casbin/Casbin.NET/issues/227
- [ ] https://github.com/casbin/Casbin.NET/issues/228
